Repository VineeTagarwaL-code/v3cn-docs, pull requests merged in 2025-03, with the labels that each got.

#9 feat: added doc page with installation steps & provided for base for future doc implementation
  bun.lockb
  public/icons/myicon.png
  src/app/docs/installation/page.tsx
  src/app/docs/introduction/page.tsx
  src/app/docs/layout.tsx
  src/app/docs/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/components/bread-crumb.tsx
  src/components/custom-sidebar.tsx
  src/components/install-tab.tsx
  src/components/pqoqubbw/book-text.tsx
  src/components/pqoqubbw/clock.tsx
  src/components/pqoqubbw/download.tsx
  src/components/pqoqubbw/moon.tsx
  src/components/pqoqubbw/search.tsx
  src/components/provider.tsx
  src/components/sidebar-wrapper.tsx
  src/components/toggle-theme.tsx
  src/components/ui/breadcrumb.tsx
  src/components/ui/input.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/separator.tsx
  src/components/ui/sheet.tsx
  src/components/ui/sidebar.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/tooltip.tsx
  src/hooks/use-mobile.tsx
  src/types/types.ts
  src/utils/constant.ts
Labels: enhancement, help wanted, good first issue

#20 fix: github graph overflow
  src/app/docs/components/github-graph/page.tsx
Labels: bug, enhancement

#21 fix: chopped image on phone mockup
  src/app/page.tsx
  src/components/landing/hero.tsx
Labels: bug
